<a href="https://colab.research.google.com/github/pawan-cpu/Learn-Python-with-Pawan-Kumar/blob/main/Copy_of_Pawan_Lesson_13_Claude_Shannon's_Algorithm_I_Class_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 13: Claude Shannon's Algorithm I

---

### Teacher-Student Tasks

In the previous lesson, we learned how to create NumPy arrays and various NumPy array functions which allows NumPy array manipulation to access data and subarrays and to reshape the arrays.

In this class, we will explore three-dimensional arrays and also understand and implement Claude Shannon's  Mind Reading algorithm.


---

#### Task 1: Three-Dimensional NumPy Arrays

An array that has a two-dimensional arrays  as its elements is called three-dimensional array. 

Let's create an array having each item as 1 with dimensions 5 blocks, 3 rows, and 3 columns using `ones()` function from the `numpy` module:

In [ ]:
# S1.1: Create an array containing '1' as its items using the 'ones()' function from the 'numpy' module.
import numpy as np
# Step 1: Always import the 'numpy' module at the beginning of the code and give it an alias (or nickname) called np. 
# We will always refer to the 'numpy' module as 'np' throughout the code.
ones=np.ones((5,3,3))
print(ones)

# Step 2: Call 'ones()' function from the np module using the dot operator.
# The 'ones()' function, requires two inputs: the dimension of the array and data-type of the items which in this case is 'int'. 


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Similarly, let us create a three-dimensional array with two 2D arrays, both containing two arrays with the values 1, 2, 3 and 4, 5, 6 using `np.array()` function.

In [ ]:
# S1.2: Create a 3D array having 2 blocks, 2 rows and 3 columns.
array1=np.array

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Thus, we can use `np.array()` function to create a three dimensional array having desired values.

---

#### Task 2: Array Length

Let's begin the lesson with array length. The length of an array (or array length) is: 

- The number of items in a one-dimensional array.

- The number of rows in a two-dimensional array.

- The number of blocks in a three-dimensional array.

To calculate the length of a NumPy array, you can use the `len()` function.

Let's create an array for all the three different dimensions and calculate their lengths using the `len()` function:




In [ ]:
# S2.1: Create a NumPy array for all the three different dimensions and calculate their lengths.
print(len(ones))
ltn=np.arange(1,25)
array5=np.arange(1,29).reshape(4,7)
print(len(ltn))
print(len(array5))


5
24
4


**Note:** You do not have to create the arrays with the exact same items. You can choose to have different items in the arrays. 

As you can see, the `len()` function gives different outputs for multi-dimensional NumPy arrays.

---

#### Task 3: The `size` Keyword

To find the number of items in a NumPy array, you can use the `size` keyword. Regardless of dimensions, the `size` keyword will always return the number of items in a NumPy array:

In [ ]:
# S3.1: Compute the number of items in the 'one_dim_ar', 'two_dim_ar' and 'three_dim_ar' NumPy arrays.
print(ones.size)
print(ltn.size)
print(array5.size)


45
24
28


**Note:** The `size` keyword is not available for a Python list.

Hence, we can easily determine the total number of items in `numpy.ndarray` object without iterating through the entire array.

---

#### Task 4: Claude Shannon Mind Reading algorithm

The Mind Reader game algorithm is built around the machine invented by Claude Shannon in 1953. He named it "A Mind Reading Machine". It predicts a player's next move based on his/her previous inputs.



**Note:** *The algorithm is quite complicated to understand and to create. For all practical purposes, you just need to know how to apply the algorithm. It is completely all right if you do not understand how to create this algorithm.*

In this algorithm, the computer looks for certain patterns in the player inputs (`Heads` or `Tails`) and tries to remember them. Furthermore, it assumes that the player will follow these patterns the next time if the same situation arises. 

The computer also contains an element of randomness. If an assumed pattern is not repeated at least twice by the player, the machine predicts `Heads` or `Tails` randomly.

The types of patterns remembered, involve the outcome of two successive plays, i.e., whether or not the player won on those plays and whether the player changed their choice between the plays and after the plays. 

There are 8 possible situations and, for each situation, a player can do two things. These 8 situations are:

1. The player **wins**, plays the **same**, and **wins** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Heads` again and wins again. In the next attempt, he/she may play either `Heads` or `Tails`.

2. The player **wins**, plays the **same**, and **loses**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Heads` again and loses. In the next attempt, he/she may play either `Heads` or `Tails`.

3. The player **wins**, plays **differently**, and **wins** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Tails`, and wins again. In the next attempt, he/she may play either `Heads` or `Tails`.

4. The player **wins**, plays **differently**, and **loses**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Tails` and loses. In the next attempt, he/she may play either `Heads` or `Tails`.

5. The player **loses**, plays the **same**, and **wins**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Heads` again and wins. In the next attempt, he/she may play either `Heads` or `Tails`.

6. The player **loses**, plays the **same**, and **loses** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Heads` again and loses again. In the next attempt, he/she may play either `Heads` or `Tails`.

7. The player **loses**, plays **differently**, and **wins**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Tails` and wins. In the next attempt, he/she may play either `Heads` or `Tails`.

8. The player **loses**, plays **differently**, and **loses** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Tails` and loses again. In the next attempt, he/she may play either `Heads` or `Tails`.

Each situation corresponds to a different cell in the memory of a machine. Within a cell, two events are registered:

1. Whether the last time this situation arose, the player played the same or different.

2. Whether or not the behavior indicated in the first point, was a repeat of the same behavior in the preceding situation. 

Consider the situation **win**, **same**, and **lose**, i.e., the second situation out of the 8 possible situations.

Suppose that the last time the second situation occurred, the player played **differently**. So **differently** is recorded in the first part of the memory cell. If at the preceding juncture, the second situation arose and the player again played **differently**, the second part of the memory cell registers this as a repeat.

If this situation arises again, the machine will assume that this is a definite pattern in the player's behavior and will play accordingly. If the player does not repeat, the machine makes predictions randomly. The memory cells are always kept up to date.


Taking inspiration from Claude Shannon's "A Mind Reading Machine", in our algorithm, we will create a three-dimensional array having 2 blocks, 2 rows, and 2 columns to keep track of the last two player inputs and the current player input:

```
[[[0, 0],
  [0, 0]],

 [[0, 0],
  [0, 0]]]
```

So, for a combination of the last two player inputs and the current player input, if a situation is repeated then we will store `1` in the second column of the array otherwise, we will store `0`. 


Here's the implementation of Cluade Shannon's "A Mind Reading Machine" based algorithm in Python. We will cover half of it in this class and the remaining half in the next class as it is very complicated and a very lengthy algorithm.

```
import random
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int) 

last_1 = 0
last_2 = 0

scores = [0, 0] # [computer_score, player_score]

def update_inputs(current):
  global last_1, last_2
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1 
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0 
    inputs[last_2][last_1][0] = current
  
  last_1 = current # current becomes last_1 
  last_2 = last_1 # last_1 becomes last_2 
    
def prediction():
  if inputs[last_2][last_1][1] == 1: 
    predict = inputs[last_2][last_1][0]    
  else:
    predict = random.randint(0, 1)  
  return predict

def update_scores(predicted, player_input):  
  if predicted == player_input:
    scores[0] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score: ", scores[1]) 
        
  else:
    scores[1] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 

def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0
  
  for i in range(2):
    scores[i] = 0

def gameplay():
  reset()
  valid_entries = ['0', '1']
  while True:
    predicted = prediction()
    player_input = input("\nEnter either 1 or 0: ")
    
    while player_input not in valid_entries:
      print("\nInvalid Input!")
      player_input = input("Please enter either 1 or 0: ")
    
    player_input = int(player_input)  
    update(player_input)
    update_scores(predicted, player_input)
        
    if scores[0] == 50:
      print("\nBad Luck, Computer Wins!\n")
      break
        
    elif scores[1] == 50:
      print("\nCongrats, You Won!\n")
      break
```

Let's get started.

---

#### Task 5: Last Two Players Inputs

Let's create two variables: `last_1` and `last_2` to keep a track of the last two inputs of a player. Also, let's set their initial values equal to `0`. 

In [ ]:
# S5.1: Create two variables; 'last_1' and 'last_2' with 0 as their initial values.



- `last_1` stores the last player input. 

- `last_2` stores the second-last player input.




---

#### Task 6: NumPy Array

Now, let's create a three-dimensional NumPy array which has 2 blocks, 2 rows, and 2 columns such that all the initial items are `0`. Let's store it in the `inputs` variable:

```
inputs = [[[0 0],
           [0 0]],

          [[0 0],
           [0 0]]]
```

In [ ]:
# S6.1: Create a 3D NumPy array of size (2, 2, 2) whose all the elements are 0.


The `inputs` array acts as a memory for the Mind Reader game. 

- The first column (`column_index = 0`) of the `inputs` array will store the current player input.

- The second column (`column_index = 1`) will store whether a situation (out of the 8 possible situations) is repeated or not. The 8 possible situations are:

|Situation|Second-Last Play|Last Play|Current Player Input|
|-|-|-|-|
|1.|`0`|`0`|`0`|
|2.|`0`|`0`|`1`|
|3.|`0`|`1`|`0`|
|4.|`0`|`1`|`1`|
|5.|`1`|`0`|`0`|
|6.|`1`|`0`|`1`|
|7.|`1`|`1`|`0`|
|8.|`1`|`1`|`1`|

Where `0` denotes `Heads` and `1` denotes `Tails`.

The blocks in the `inputs` array denote the second-last play. 

- If `last_2 = 0`, then the `last_1` value will go to the first/second row of the **first** block.

- If `last_2 = 1`, then the `last_1` value will go to the first/second row of the **second** block.

<img src = 'https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/inputs_array.png' width=600>

At a time, the **current player input** will either go to the first block or second block because the second-last play would either be `0` or `1`.

Here are the possible ways in which the current player inputs will be recorded in the first block.

1. All the items in the first column are `0`:

  ```
  [[0, is_a_repeat],
    [0, is_a_repeat]]
  ```

2. The item in the first row and first column is `0` but the item in the second row and the first column is `1`:

  ```
  [[0, is_a_repeat],
    [1, is_a_repeat]]
  ```

3. The item in the first row and first column is `1` but the item in the second row and the first column is `0`:

  ```
  [[1, is_a_repeat],
    [0, is_a_repeat]]
  ```

4. All the items in the first column are `1`:

  ```
  [[1, is_a_repeat],
    [1, is_a_repeat]]
  ```

The value of `is_a_repeat` is either `0` or `1`.

  - The value `0` or `1` in the first column represents whether the player played `Heads` or `Tails`, respectively, in the last attempt.
  
  - The value `0` or `1` in the second column represents whether a situation (a combination of `last_2, last_1`,if we can shift the values at c and current player input) is repeated or not. The value `0` means the situation is NOT repeated and `1` means the situation is repeated.

The second block will also have the exact same possibilities.

All right! We will stop here now. In the next class, we will create the following functions to complete the algorithm:

1. The `update_inputs()` function.

2. The `prediction()` function.

3. The `update_scores()` function

4. The `reset()` function.

5. The `gameplay()` function.

---