<a href="https://colab.research.google.com/github/pawan-cpu/Learn-Python-with-Pawan-Kumar/blob/main/Copy_of_2021_11_22_Pawan_Lesson14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 14: Claude Shannon II

---

### Teacher-Student Tasks


In the previous class, we completed half of Claude Shannon's "A Mind Reading Machine" based algorithm.


As a quick recap, in this algorithm:

1. The computer looks for certain patterns in the player inputs (`Heads` or `Tails`) and tries to remember them. Furthermore, it assumes that the player will follow these patterns the next time if the same situation arises. 

2. If an assumed pattern is not repeated at least twice by the player, the machine predicts `Heads` or `Tails` randomly.

The types of patterns remembered, involve the outcome of two successive plays, i.e., whether or not the player won on those plays and whether the player changed their choice between the plays and after the plays. 

There are 8 possible situations and, for each situation, a player can do two things. These 8 situations are:

1. The player **wins**, plays the **same** and **wins** again. The player then plays the same or plays differently.

2. The player **wins**, plays the **same** and **loses**. The player then plays the same or plays differently.

3. The player **wins**, plays **differently** and **wins** again. The player then plays the same or plays differently.

4. The player **wins**, plays **differently** and **loses**. The player then plays the same or plays differently.

5. The player **loses**, plays the **same** and **wins**. The player then plays the same or plays differently.

6. The player **loses**, plays the **same** and **loses** again. The player then plays the same or plays differently.

7. The player **loses**, plays **differently** and **wins**. The player then plays the same or plays differently.

8. The player **loses**, plays **differently** and **loses** again. The player then plays the same or plays differently.

Each situation corresponds to a different cell in the memory of a machine. Within a cell, two events are registered:

1. Whether the last time this situation arose, the player played the same or different.

2. Whether or not the behaviour indicated in the first point, was a repeat of the same behaviour in the preceding situation. 

We created a three-dimensional NumPy array having 2 blocks, 2 rows and 2 columns to keep track of the last two player inputs and the current player input.

```
[[[0, 0],
  [0, 0]],

 [[0, 0],
  [0, 0]]]
```

So, for a combination of the last two player inputs and the current player input, if a situation is repeated then we will store `1` in the second column of the array otherwise, we will store `0`. 

Let's quickly run the codes for the activities that were covered in the last class and begin this class from **Activity 1: The `update_inputs()` Function**

---

#### Last Two Players Inputs

The `last_1` and `last_2` variables keep track of the last two inputs of a player. 

In [ ]:
# Create two variables; 'last_1' and 'last_2' with 0 as their initial values.
last_1 = 0
last_2 = 0


- `last_1` stores the last player input. 

- `last_2` stores the second-last player input.




---

#### The `inputs` Array

In [ ]:
# Create a 3D NumPy array of size (2, 2, 2) whose all the elements are 0.
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)
inputs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

The `inputs` array acts as a memory for the Mind Reader game. 

- The first column (`column_index = 0`) of the `inputs` array will store the current player input.

- The second column (`column_index = 1`) will store whether a situation (out of the 8 possible situations) is repeated or not. The 8 possible situations are:

|Situation|Second-Last Play|Last Play|Current Player Input|
|-|-|-|-|
|1.|`0`|`0`|`0`|
|2.|`0`|`0`|`1`|
|3.|`0`|`1`|`0`|
|4.|`0`|`1`|`1`|
|5.|`1`|`0`|`0`|
|6.|`1`|`0`|`1`|
|7.|`1`|`1`|`0`|
|8.|`1`|`1`|`1`|

where `0` denotes `Heads` and `1` denotes `Tails`.

The blocks in the `inputs` array denote the second-last play. 

- If `last_2 = 0`, then the `last_1` value will go to the first/second row of the **first** block.

- If `last_2 = 1`, then the `last_1` value will go to the first/second row of the **second** block.

<img src = 'https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/inputs_array.png' width=600>

At a time, the **current player input** will either go to the first block or second block because the second-last play would either be `0` or `1`.

Here are the possible ways in which the current player inputs will be recorded in the first block.

1. All the items in the first column are `0`.

  ```
  [[0, is_a_repeat],
    [0, is_a_repeat]]
  ```

2. The item in the first row and first column is `0` but the item in the second row and the first column is `1`.

  ```
  [[0, is_a_repeat],
    [1, is_a_repeat]]
  ```

3. The item in the first row and first column is `1` but the item in the second row and the first column is `0`.

  ```
  [[1, is_a_repeat],
    [0, is_a_repeat]]
  ```

4. All the items in the first column are `1`.

  ```
  [[1, is_a_repeat],
    [1, is_a_repeat]]
  ```

The value of `is_a_repeat` is either `0` or `1`.

  - The value `0` or `1` in the first column represents whether the player played `Heads` or `Tails`, respectively, in the last attempt.
  
  - The value `0` or `1` in the second column represents whether a situation (a combination of `last_2, last_1` and current player input) is repeated or not. The value `0` means the situation is NOT repeated and `1` means the situation is repeated.

The second block will also have the exact same possibilities.

---

#### Task 1: The `update_inputs()` Function

Now, we are going to update the entries of the `inputs` array by creating a function. Let's name this function as `update_inputs()`. It should take `current` player input as an input and should not return anything. It should just update the player inputs in the `inputs` array.

For a row in a block, if an item in the $1^{st}$ column is the same as the `current` player input, then set the value in the $2^{nd}$ column equal to `1`, and set the value in the $1^{st}$ column equal to the `current` player input.

```
if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1 
    inputs[last_2][last_1][0] = current
```

Otherwise, set the value in the $2^{nd}$ column equal to `0` and set the value in the $1^{st}$ column equal to the `current` value.

```
inputs[last_2][last_1][1] = 0 
    inputs[last_2][last_1][0] = current
```

Then, the `current` value should become the `last_1` value and the `last_1` value should become the `last_2` value.

```
  last_2 = last_1 
  last_1 = current 
```

In [ ]:
# S1.1: Create the 'update_inputs()' function.
def update_inputs(current):
  if inputs[last_2][last_1][0]==current:
    inputs[last_2][last_1][1]=1
    inputs[last_2][last_1][0]=current
  else:
    inputs[last_2][last_1][1]=0
    inputs[last_2][last_1][0]=current
  last_2=last_1
  last_1=current
  
    
    



---

#### Task 2: The `prediction()` Function

Now, let's create a function and name it `prediction()`. This function will allow a computer to make predictions based on the player inputs in the last two plays.

For a row in a block, if the value in the $2^{nd}$ column is `1`, then the `prediction()` function should return the item stored in the $1^{st}$ column as the predicted value. 

```
if inputs[last_2][last_1][1] == 1: 
    predict = inputs[last_2][last_1][0]
```

Else, either return `0` or `1` randomly as the predicted value.

```
else:
    predict = random.randint(0, 1)
```

Essentially, if the item in the second column is `1`, then return the item stored in the first column as the predicted value. Else, predict `0` or `1` randomly.

In [ ]:
# S2.1: Create the 'prediction()' function which returns the predicted value.
import random
def prediction():
  if inputs[last_2][last_1][1]==1:
    predict=inputs[last_2][last_1][0]
  else:
    predict=random.randint(0,1)
  return predict
    
    

    
    



---

#### Task 3: The `update_scores()` Function

Next, we need to create the `update_scores()` function that we created in the first few classes. It should take the `predicted` and the current `player_input` values as an input and then update the scores for both the computer and the player at every player input. It should also print the current scores at every player input.

To keep the scores, instead of creating two separate variables for the computer and the player, we will create a list. *The first item in the list will represent the computer score and the second item will represent the player score.*

Initially, both the items in the `scores` list will be zero. At every player input, the scores should get updated.

In [ ]:
# S3.1: Create the 'update_scores()' function to keep the scores for both the computer and the player. It should not return anything.
scores = [0, 0] 

def update_scores(predicted, player_input):
  if predicted == player_input:
    scores[0] =  scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 
               
  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1])


---

#### Task 4: The `reset()` Function

Now let's create a function which resets the `inputs` array items and `scores` list to `0`. The `inputs` array values and the `scores` list values must be reset to `0` before a player plays the game again. Otherwise, it will not be a fair game to the player.

Moreover, if a player stops playing the game before finishing it, then also the `inputs` array and the `scores` list will have some values stored in it. So, before restarting the game, the `inputs` array values and the `scores` values must be reset to zero.

In [ ]:
# S4.1: Create the 'reset()' function which resets the values of the 'inputs' items to 0.
def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0

  for i in range(len(scores)):
    scores[i] = 0

---

#### Task 5: Putting Everything Together

Now put all the components of the Mind Reader game algorithm in one place.

In [ ]:
# S5.1: Put all the functions and variables of the Mind Reader game algorithm here.
import random
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int) 

last_1 = 0
last_2 = 0

scores = [0, 0] # [computer_score, player_score]

def update_inputs(current):
  global last_1, last_2
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1 
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0 
    inputs[last_2][last_1][0] = current
  
  last_2 = last_1 
  last_1 = current 
    
def prediction():
  if inputs[last_2][last_1][1] == 1: 
    predict = inputs[last_2][last_1][0]    
  else:
    predict = random.randint(0, 1)  
  return predict

def update_scores(predicted, player_input):  
  if predicted == player_input:
    scores[0] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 
        
  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 

def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0
  
  for i in range(2):
    scores[i] = 0


---

#### Task 6: The `gameplay()` Function

Now, let's create the `gameplay()` function to run the Mind Reader game. We have used this function many times in earlier classes. There is no major change in it. However, it should first execute the `reset()` function so that whenever a player plays this game again, it should reset the `inputs` values and the `scores` values.


For the testing purpose, let's run the Mind Reader game till either the player or the computer has reached a score of 20 points. If we run this game till 50 points, then the testing will take a very long time. Later you can change the scoring to 50 points.

In [ ]:
# S6.1: Create the 'gameplay()' function.
def gameplay():
  reset()
  print(inputs) # To verify whether the 'reset()' function, resets the 'inputs' and 'scores' values or not print their values.
  print(scores)
  valid_entries = ['0', '1']
  while True:
    predicted = prediction()
    player_input = input("\nEnter either 1 or 0: ")
    
    while player_input not in valid_entries:
      print("\nInvalid Input!")
      player_input = input("Please enter either 1 or 0: ")
    
    player_input = int(player_input)
    update_inputs(player_input)
    update_scores(predicted, player_input)
    if scores[0] == 20:
      print("\nBad Luck, Computer Wins!\n")
      break
        
    elif scores[1] == 20:
      print("\nCongrats, You Won!\n")
      break

Now, run the game by executing the `gameplay()` function.

In [ ]:
# S6.2: Run the game by executing the 'gameplay()' function.
gameplay()

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[0, 0]

Computer Score: 0 
Player Score: 1

Computer Score: 0 
Player Score: 2

Computer Score: 1 
Player Score: 2


Finally, we have implemented the algorithm for the Mind Reader game that allows a computer to predict a player's next move accurately.

 In the next class, we  will perform some of the mathematical operations using NumPy arrays and we will also compare the performance of a NumPy array with a Python list.

---